 SET SERVEROUTPUT ON;
/

CREATE OR REPLACE PROCEDURE tableCONSTRAINTS (TABLENAME IN VARCHAR2) AS
BEGIN
  FOR INDX IN (SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME=TABLENAME) LOOP
    DBMS_OUTPUT.PUT_LINE('OWNER: '||INDX.OWNER||' CONSTRAINT NAME: '||INDX.CONSTRAINT_NAME||' CONSTRAINT_TYPE: '||INDX.CONSTRAINT_TYPE);
  END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE userCONSTRAINTS (USERNAME IN VARCHAR2) AS
BEGIN
  FOR INDX IN (SELECT * FROM USER_CONSTRAINTS WHERE OWNER=USERNAME) LOOP
    DBMS_OUTPUT.PUT_LINE('CONSTRAINT NAME: '||INDX.CONSTRAINT_NAME||' CONSTRAINT_TYPE: '||INDX.CONSTRAINT_TYPE||' TABLE_NAME: '||INDX.TABLE_NAME);
  END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE ROLEFOR (USERNAME1 IN VARCHAR2) AS
BEGIN
  FOR INDX IN (SELECT * FROM USER_ROLE_PRIVS WHERE USERNAME=USERNAME1) LOOP
    DBMS_OUTPUT.PUT_LINE(INDX.USERNAME||' '||INDX.GRANTED_ROLE||' '||INDX.ADMIN_OPTION||' '||INDX.DEFAULT_ROLE||' '||INDX.OS_GRANTED);
  END LOOP;
END;
/

CREATE OR REPLACE VIEW MAX_COLUMNS_TABLE AS
SELECT TABLE_NAME, COUNT(*) AS NUMAR_COLOANE FROM USER_TAB_COLUMNS GROUP BY TABLE_NAME HAVING COUNT(*)=(SELECT MAX(COUNT(*)) FROM  USER_TAB_COLUMNS  GROUP BY TABLE_NAME) ;
/

CREATE OR REPLACE VIEW LAST_DELETED_OBJECT AS
SELECT * FROM USER_RECYCLEBIN WHERE DROPTIME=(SELECT MIN(DROPTIME) FROM USER_RECYCLEBIN) ;
/