SET SERVEROUTPUT ON;
/

drop table contract_orange_martin;
/

CREATE OR REPLACE PROCEDURE NUMBER_TABLE IS
 INSERT_NUMBERS_STRING VARCHAR2(100);
 CREATE_TABLE_QUERY VARCHAR2(200);
 NR VARCHAR2(2);
 TEL_NR VARCHAR2(10);
 v_CursorID NUMBER;
 nmb NUMBER;
 tableName VARCHAR2(40);
 boss VARCHAR2(10);
BEGIN
  SELECT ENAME INTO boss FROM EMP WHERE COMM = (SELECT MAX(COMM) FROM EMP);  
  tableName :='CONTRACT_ORANGE_'||trim(boss);
  BEGIN
   CREATE_TABLE_QUERY :='CREATE TABLE '||tableName||' AS SELECT EMPNO, CAST(NULL AS NUMBER(10)) AS NR_TEL FROM EMP ';
   v_CursorID := DBMS_SQL.OPEN_CURSOR;
   DBMS_SQL.PARSE(v_CursorID,CREATE_TABLE_QUERY,DBMS_SQL.NATIVE);
   nmb:=DBMS_SQL.EXECUTE(v_CursorID);
   EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR WHEN CREATING A TABLE, MAYBE IT ALREADY EXISTS');
  END;
  FOR INDX IN (SELECT EMPNO,SAL FROM EMP) LOOP
    v_CursorID := DBMS_SQL.OPEN_CURSOR;
    SELECT 14-COUNT(*) INTO NR FROM (SELECT * FROM EMP ORDER BY SAL) WHERE SAL<INDX.SAL;
    TEL_NR:='07410000';
    IF NR<10 THEN
      TEL_NR:=TEL_NR ||'0';
    END IF;
    TEL_NR:=TEL_NR||NR;
    INSERT_NUMBERS_STRING:='UPDATE '|| tableName || ' SET NR_TEL=:B WHERE EMPNO=:C';
    DBMS_SQL.PARSE(v_CursorID,INSERT_NUMBERS_STRING,DBMS_SQL.NATIVE);
    DBMS_SQL.BIND_VARIABLE(v_CursorID,':B',TEL_NR);
    DBMS_SQL.BIND_VARIABLE(v_CursorID,':C',INDX.EMPNO);
    nmb:=DBMS_SQL.EXECUTE(v_CursorID);
  END LOOP;
  END;
/

BEGIN
  NUMBER_TABLE;
END;
/