SET SERVEROUTPUT ON;
/
CREATE OR REPLACE PROCEDURE JOB_TABLES IS
 CREATE_TABLE_QUERY VARCHAR2(250); 
 v_CursorID NUMBER;
 nmb NUMBER;
BEGIN
  FOR INDX IN (SELECT UNIQUE JOB FROM EMP) LOOP
    v_CursorID := DBMS_SQL.OPEN_CURSOR;
    BEGIN
    CREATE_TABLE_QUERY:='CREATE TABLE EMP_'||INDX.JOB||' AS SELECT * FROM EMP WHERE JOB=''INDX.JOB'' ';
    DBMS_SQL.PARSE(v_CursorID,CREATE_TABLE_QUERY ,DBMS_SQL.NATIVE);
    nmb:=DBMS_SQL.EXECUTE(v_CursorID);
    EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR WHEN CREATING A TABLE, MAYBE IT ALREADY EXISTS');
    END;
  END LOOP;
END;
/

DECLARE
NMB NUMBER;
v_CursorID NUMBER;
BEGIN
 JOB_TABLES;
 v_CursorID := DBMS_SQL.OPEN_CURSOR;
 DBMS_SQL.PARSE(v_CursorID,'DROP TABLE EMP_SALESMAN' ,DBMS_SQL.NATIVE);
 NMB:=DBMS_SQL.EXECUTE(v_CursorID);
END;
/