DROP TABLE DEPARTAMENTE;
/

CREATE TABLE DEPARTAMENTE OF Departament;
/

DROP TABLE TABLEMGRS;
/

CREATE TABLE tableMGRS (mngr Manager);
/

CREATE OR REPLACE PROCEDURE popDept IS
  dep Departament:=Departament();
BEGIN
  FOR IDX IN (SELECT DEPTNO,DNAME FROM DEPT) LOOP
    dep.DEPTNO:=IDX.DEPTNO;
    dep.DNAME:=IDX.DNAME;
    INSERT INTO DEPARTAMENTE VALUES(dep);
  END LOOP;  
END;
/

CREATE OR REPLACE PROCEDURE popMgr  IS
  mgr Manager:=Manager();
  nmbOfMgr INTEGER;
BEGIN
  SELECT COUNT(EMPNO) INTO nmbOfMgr FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP);
  FOR IDX IN (SELECT EMPNO FROM EMP WHERE JOB='MANAGER  ') LOOP
    SELECT EMPNO INTO mgr.EMPNO FROM EMP WHERE EMPNO=IDX.EMPNO;
    SELECT ENAME INTO mgr.ENAME FROM EMP WHERE EMPNO=IDX.EMPNO;
    SELECT COUNT(EMPNO) INTO mgr.nrEmp FROM EMP WHERE EMPNO IN (SELECT EMPNO FROM EMP WHERE MGR=mgr.EMPNO );
    SELECT SAL INTO mgr.SAL FROM EMP WHERE EMPNO=IDX.EMPNO;
    SELECT REF(DEPT) INTO mgr.DEPT FROM DEPARTAMENTE DEPT WHERE DEPT.DEPTNO=(SELECT DEPTNO FROM EMP WHERE EMPNO=mgr.EMPNO ); 
    INSERT INTO tableMGRS values(MGR);
  END LOOP;
END;
/

DECLARE
BEGIN
  popDept;
  popMgr;
END;
/

SELECT D.mngr.ename ,D.mngr.empno,D.mngr.sal,D.mngr.dept.deptno,D.mngr.dept.dname,D.mngr.nremp AS nr_angajati FROM tableMGRS D ORDER BY mngr;


