CREATE OR REPLACE TYPE Departament AS OBJECT ( 
  deptno INTEGER,
  dname VARCHAR(14),
  CONSTRUCTOR FUNCTION Departament RETURN SELF AS RESULT
);
/

CREATE OR REPLACE TYPE BODY Departament AS 
  CONSTRUCTOR FUNCTION Departament RETURN SELF AS RESULT AS
    BEGIN
      RETURN;
    END;
END;
/